### ISSUE TITLE
about category

### ISSUE THREAD

**Issue by Sunyandong-CS** [Rabbbbbbit/iOSReview#1]
一个类添加了多个category，且多个category中实现了同一个方法,那么会先调用哪个呢？category可以实现的最根本原因应该是Class结构体里面objc_method_list是个指向指针的指针，我们可以修改这个指针的指向

**Comment by gozelus** [comment]
>需要注意的时，category中的方法其实并没有覆盖原类中的同名方法，只是单纯地添加到方法列表中而已。但是由于objc在方法调用中查找到类对象中的方法列表时，只要找到了第一个对应消息中的选择子的方法，就认为是找到了对应的方法并调用。所以形成了category中的方法会覆盖原类中的同名方法的假象。

如果只是改变指针指向，那么`+Load`方法的表现应该不是现在这样。
